config/routes.rb
Rails.application.routes.draw do
	namespace :admin do
		resources :projects, except: [:show]
		get 'cancel', to: "projects#cancel"
	end
	get '/projects', to: "application#projects"
	root to: "application#home"
	get "/my-cv", to: "application#cv"
	resources "contacts", only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name, :validate => true
	attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
  	{
  		:subject => "Message From My Resume",
  		:to => "gooryalhamed@gmail.com",
  		:from => %("#{name}" <#{email}>)
  	}
  end
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
	before_action :find_project, only: [:edit, :update, :destroy]

	def index
		@projects = Project.all
		@project = Project.new
	end

	def create
		@project = Project.new(params_project)
		uploaded_io = params[:project][:image]
		if !uploaded_io.blank?
			File.open(Rails.root.join('public','uploads',uploaded_io.original_filename), "wb") do |file|
				file.write(uploaded_io.read)
			end
		end
		if @project.save
			@project.update(image: uploaded_io.original_filename) if !uploaded_io.blank?
			redirect_to admin_projects_path
		else
			render :new
		end
	end

	def cancel
	end

	def update
		uploaded_io = params[:project][:image]
		if !uploaded_io.blank?
			File.open(Rails.root.join('public','uploads',uploaded_io.original_filename), "wb") do |file|
				file.write(uploaded_io.read)
			end
		end
		if @project.update(params_project)
			@project.update(image: uploaded_io.original_filename) if !uploaded_io.blank?
			redirect_to admin_projects_path
		else
			render :edit
		end
	end

	def destroy
		@project.destroy
	end

	private
	def find_project
		@project = Project.find(params[:id])
	end
	def params_project
		params.require(:project).permit(:title, :description, :image, :link, :source)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def home
  end

  def cv
  end

  def projects
  	@projects = Project.all
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_for @project do |f|%>
<div class="row">
	<div class="col-sm-6">
		<div class="field">
			<%= f.text_field :title, placeholder: "title", required: true %>
		</div>
		<div class="field">
			<%= f.text_area :description, placeholder: "description", required: true %>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="field">
			<%= f.text_field :source, placeholder: "source code's link", required: true %>
		</div>
		<div class="field">
			<%= f.text_field :link, placeholder: "project's link", required: true %>
		</div>
		<div class="field">
			<%= f.file_field :image %>
		</div>
	</div>
</div>

<% end %>

app/views/admin/projects/_project.html.erb
<div class="row" id="<%=@project.id%>">
	<%= image_tag("/uploads/#{@project.image}", :class=>"col-sm-3 col-xs-4")%>
	<div class="col-sm-8">
		<h4 class="pro-name"><%= @project.title %></h4>
		<p><%= @project.description %></p>
		<p>Source Code: <%= @project.source %></p>
		<p>project's link: <%= @project.link %></p>
		<div class="feedback">
			<i class="fa fa-star-o" aria-hidden="true"></i> <span>Stars</span>
			<i class="fa fa-eye" aria-hidden="true"></i> Viewes
		</div>
	</div>
	<div class="dropdown col-sm-1">
		<span class="dropdown-toggle" data-toggle="dropdown">
			<i class="fa fa-ellipsis-v" aria-hidden="true"></i>
		</span>

		<ul class="dropdown-menu">
			<li>
				<%= link_to 'Edit', edit_admin_project_path(@project) %>
			</li>
			<li>
				<%= link_to 'Delete',admin_project_path(@project), method: :delete, data: {confirm: 'Are you sure you want to delete this project?'}, remote: true  %>
			</li>
		</ul>
	</div> 
</div>

app/views/admin/projects/cancel.js.erb
$('#new_project_div').remove();

app/views/admin/projects/destroy.js.erb
$('div#<%=@project.id%>').remove();

app/views/admin/projects/edit.html.erb
<%= form_for([:admin, @project]) do |f|%>
<div class="row">
	<div class="col-sm-6">
		<div class="field">
			<%= f.text_field :title, placeholder: "title", required: true %>
		</div>
		<div class="field">
			<%= f.text_area :description, placeholder: "description", required: true, rows: "6" %>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="field">
			<%= f.text_field :source, placeholder: "source code's link", required: true %>
		</div>
		<div class="field">
			<%= f.text_field :link, placeholder: "project's link", required: true %>
		</div>
		<div class="field">
			<%= f.file_field :image %>
		</div>
		<div class="field">
			<%= f.submit %>
		</div>
	</div>
</div>
<% end %>

app/views/admin/projects/index.html.erb
<div id="login">
	<h2>Admin Spac</h2>
	<span>please verify your identity</span>
	<input type="password" id="password" placeholder="Secret code">
	<button id="ok">Go</button>
</div>
<div id="projects_wrapper" class="hidden">
	<% @projects.each do |proj| %>
	<div class="row" id="<%=proj.id%>">
		<%= image_tag("/uploads/#{proj.image}", :class=>"col-sm-3 col-xs-4")%>
		<div class="col-sm-8">
			<h4 class="pro-name"><%= proj.title %></h4>
			<p><%= proj.description %></p>
			<p>Source Code: <%= proj.source %></p>
			<p>Project's link: <%= proj.link %></p>
			<div class="feedback">
				<i class="fa fa-star-o" aria-hidden="true"></i> <span>Stars</span>
				<i class="fa fa-eye" aria-hidden="true"></i> Viewes
			</div>
		</div>
		<div class="dropdown col-sm-1">
			<span class="dropdown-toggle" data-toggle="dropdown">
				<i class="fa fa-ellipsis-v" aria-hidden="true"></i>
			</span>

			<ul class="dropdown-menu">
				<li>
					<%= link_to 'Edit', edit_admin_project_path(proj) %>
				</li>
				<li>
					<%= link_to 'Delete',admin_project_path(proj), method: :delete, data: {confirm: 'Are you sure you want to delete this project?'}, remote: true  %>
				</li>
			</ul>
		</div> 
	</div>
	<% end %>
	<i class="fa fa-plus-circle"></i>
</div>
<div id="new_project_div" class="hidden">
	<h3>Add a new project</h3>
	<%= form_for([:admin, @project]) do |f| %>
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<div class="row">
		<div class="col-sm-6">
			<div class="field">
				<%= f.text_field :title, placeholder: "title", required: true %>
			</div>
			<div class="field">
				<%= f.text_area :description, placeholder: "description", required: true, rows: "6" %>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="field">
				<%= f.text_field :source, placeholder: "source code's link", required: true %>
			</div>
			<div class="field">
				<%= f.text_field :link, placeholder: "project's link", required: true %>
			</div>
			<div class="field">
				<%= f.file_field :image %>
			</div>
			<div class="field">
				<%= f.submit %>
				<%= link_to 'Cancel',admin_cancel_path, remote: true %>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/application/cv.html.erb
<header class="clearfix">
	<div class="col-xs-6">
		<h1>CV</h1>
		<a href="my-resume.pdf" download class="tooltip1">
			<i class="fa fa-download" aria-hidden="true">
				<span class="tooltiptext">download CV</span>
			</i>
		</a>
		<h2>Yardagan Al Hamed</h2>
		<p>Erbil/Iraq</p>
		<p>E-mail: gooryalhamed@gmail.com</p>
		<ul class="list-inline">
			<li><a href="https://www.facebook.com/goory.alhamed" target="_blank"><i class="fa fa-facebook"></i></a></li>
			<li><a href="https://github.com/gooryalhamed" target="_blank"><i class="fa fa-github"></i></a></li>
			<li><a href="https://www.youtube.com/channel/UCeXZ7WibE8Fb-2EnTHBqhDw" target="_blank"><i class="fa fa-youtube"></i></a></li>
			<li><a href="https://www.linkedin.com/in/yardagan-al-hamed-055702140/" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
		</ul>
	</div>
	<%= image_tag("my-image.jpg", :class=>"col-xs-6 thumbnail")%>
</header>
<div class="row">
	<div class="col-md-8">
		<h4>Professtional Info</h4><hr>
		<p>Junior web developer. Skilled at creating web applications and designing websites. Excellent written and oral communication skills. Cpable of work under pressure and work with a team.</p>

		<h4>Work Experience</h4><hr>
		<span class="work-title">Data Entry</span>
		<span>2014-2016 /ERC</span>
		<p>I worked as data entry in the camp management in Qushtapa camp. I was responsible for managing the database system for the camp and the job center.</p>

		<span class="work-title">Computer Teacher</span>
		<span>2014-2015 /NRC</span>
		<p>I taught basic computer skills for youth refugees such as windows,word and power point.</p>

		<span class="work-title">Coding Trainer</span>
		<span>2017 /IOM & Re:Coded</span>
		<p>I taught scratch video game design for kids (12-18 years old) in a summer bootcamp for one month.
		</p>

		<span class="work-title">Arabic Teacher</span>
		<span>2017 /NATAKALLAM</span>
		<p>I work as Arabic teacher/conversation partner for natakallam. I help English speakers to improve their Arabic speaking,reading and listening skills. I taught more than ten students from different countries around the world.</p>

		<h4>Education</h4><hr>
		<span class="work-title">Damascus University - Computer Engineering</span>
		<span>2007-2013</span>
		<p>I studied computer engineering at the university of Damascus - Mechanical and Electrical Engineering college.</p>
		<span class="work-title">Flatiron School - Full-Stack Web Development</span>
		<span>2017</span>
		<p>I studied full-stack web developemnt at 'flatiron school' over learn.co platform for seven months. I created many web applications after graduation.</p>
	</div>
	<div class="col-md-4">
		<h4>Programming Skills</h4><hr>
		<div class="container">
			<p>Ruby On Rails</p>
			<p>Sqlite3</p>
			<p>Postgresql</p>
			<p>HTML</p>
			<p>CSS</p>
			<p>SASS</p>
			<p>Javascript</p>
			<p>Jquery</p>
			<p>AJAX & API</p>
		</div>

		<h4>Computer Skills</h4><hr>
		<div class="container">
			<p>Data analysis using Excel</p>
			<p>WIX website builder</p>
			<p>SQL Server</p>
			<p>MS Office</p>
			<p>Data collection software (kobo toolbox)</p>
		</div>

		<h4>Languages</h4><hr>
		<div class="container">
			<p>English: very good written and spoken</p>
			<p>Arabic: native speaker</p>
			<p>Kurdish: native speaker</p>
		</div>
	</div>
</div> <!-- end row -->

app/views/application/home.html.erb
<header class="clearfix">
	<%= image_tag("myimg.jpg", :class=>"col-sm-4 thumbnail") %>
	<div class="col-sm-5">
		<div class="row">
			<div class="col-xs-12">
				<span id="hello">HELLO,</span><br>
				<span id="availabl">I'm available for work.</span>
				<p id="desc">I am an open-minded full-stack web developer. I have high technical skills in creating websites,web applications and designing database management systems. I aspire to work in a challenging environment where I can use my creative problem solving skills. </p>
			</div>
		</div>
		<div class="row text-center" id="mycv">
			<div class="col-xs-12">
				<a class="button" href="/my-cv">MY CV</a>
			</div>
		</div>
	</div>
	
	<div class="col-sm-3" id="first-col">
		<div class="info-item">
			<p class="info-title">Available For:</p>
			Web development<br>
			DBMS development
		</div>
		<div class="info-item">
			<p class="info-title">Website:</p>
			gooryalhamed.github.io
		</div>
		<div class="info-item">
			<p class="info-title">Email:</p>
			gooryalhamed@gmail.com
		</div>
		<div class="info-item">
			<p class="info-title" id="social">Social Links:</p>
			<ul class="list-inline">
				<li><a href="https://github.com/gooryalhamed" target="_blank"><i class="fa fa-github"></i></a></li>
				<li><a href="https://www.youtube.com/channel/UCeXZ7WibE8Fb-2EnTHBqhDw" target="_blank"><i class="fa fa-youtube"></i></a></li>
				<li><a href="https://www.linkedin.com/in/yardagan-al-hamed-055702140/" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</div>
</header>
<div class="row">
	<div class="col-sm-4">
		<h4>TESTIMONIAL</h4>
		<p class="say">"Yardagan is one of our brightest fellows."</p>
		<p class="reference">Alexandra Clare - Founder of Re:Coded organization</p>
		<p class="say">"Your mind is sharp,you work hard and you will be a gift to any company or organization or business."</p>
		<p class="reference">Audrey Watne - Country Manager of Re:Coded organization</p>
	</div>

	<div class="col-sm-4">
		<h4>FAVORITE QUOTE</h4>
		<p class="say">"Life is the biggest challenge and to be successful, you have to beat your fears."</p>
		<p class="say">"Every thing needs love to be creative."</p>
	</div>
	<div class="col-sm-4">
		<h4>RECENT PROJECT</h4>
		<p>An interactive check list built with rails and using ajax technique. You can see it on github, just follwo the link below:</p>
		<a href="https://github.com/gooryalhamed/checklist-ajax" target="_blank">
			Source code <i class="fa fa-code"></i>
		</a>
		<a href="https://checklist-ajax.herokuapp.com/" target="_blank">
			The project <i class="fa fa-stop-circle-o"></i>
		</a>
	</div>
</div>

app/views/application/projects.html.erb
<header>
	<div class="container">
		<h1>PROJECTS</h1>
		<p>A list of open source projects I built. Your feedback is much appreciated.</p>
	</div>
</header>
<% @projects.each do |proj| %>
<div class="row">
	<%= image_tag("/uploads/#{proj.image}", :class=>"col-sm-3 col-xs-4")%>
	<div class="col-sm-8">
		<h4 class="pro-name"><%= proj.title %></h4>
		<p><%= proj.description %></p>
		<div class="feedback">
			<i class="fa fa-star-o" aria-hidden="true"></i> <span>Stars</span>
			<i class="fa fa-eye" aria-hidden="true"></i> Viewes
		</div>
	</div>
	<div class="dropdown col-sm-1">
		<span class="dropdown-toggle" data-toggle="dropdown">
			<i class="fa fa-ellipsis-v" aria-hidden="true"></i>
		</span>
		
		<ul class="dropdown-menu">
			<li>
				<a href="<%= proj.source %>" target="_blank">
					source code
				</a>
			</li>
			<li>
				<a href="<%= proj.link %>" target="_blank">
					see the project
				</a>
			</li>
		</ul>
	</div> 
</div>
<hr>
<% end %>

app/views/contacts/create.html.erb
<div id="flash-message">
	<% flash.each do |key, value| %>
	<div>
		<%= value %>
	</div>
	<% end %>
</div>

app/views/contacts/new.html.erb
<header>
  <div id="contact-wrap">
    <div class="row">
      <div class="col-sm-6">
        <p id="myname">Yardagan Al Hamed</p>
        <p>Erbil-Iraq-Qushtapa Camp</p>
        <p>Email: gooryalhamed@gmail.com</p>
        <ul class="list-inline">
          <li><a href="https://github.com/gooryalhamed" target="_blank"><i class="fa fa-github"></i></a></li>
          <li><a href="https://www.youtube.com/channel/UCeXZ7WibE8Fb-2EnTHBqhDw" target="_blank"><i class="fa fa-youtube"></i></a></li>
          <li><a href="https://www.linkedin.com/in/yardagan-al-hamed-055702140/" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
        </ul>
      </div>

      <div class="col-sm-6">
       <h1>CONTACT ME</h1>
       <p>looking forward to recieve your email</p>
       <%= form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>

       <%= f.text_field :name, :required => true, :placeholder => "Your Name" %>
       
       <%= f.email_field :email, :required => true, :placeholder => "Your Email" %>

       <%= f.text_field :message, :as => :text, :required => true,:placeholder => "Your Message", :id => "msg" %>
       <%= f.submit 'Send'%>
      <% end %>
    </div>
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>My Resume</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application', media: 'all' %>
</head>

<body>
	<div id="wrapper">
		<!-- navbar -->
		<nav class="navbar custom-header">
			<div class="container-fluid">
				<div class="navbar-header">
					<a>
						<h1>Yardagan &nbsp;&nbsp;<span style="color:#bfbfbf">Hamed</span>
						</h1>
						<span id="career">Web Developer</span>
					</a>
					<button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-links">
						<i class="fa fa-bars"></i>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="navbar-links">
					<ul class="nav navbar-nav navbar-right">
						<li class="text-center">
							<a href="/" id="home">HOME</a>
						</li>
						<li class="text-center">
							<a href="/my-cv" id="cv">CV</a>
						</li>
						<li class="text-center">
							<a href="/projects" id="projects">PROJECTS</a>
						</li>
						<li class="text-center">
							<a href="/contacts/new" id="contact">CONTACT</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container" id="content">
			<%= yield %>
		</div>
	</div>
	<!-- footer -->
	<footer class="text-center">
		<p>copyrights&copy;2017</p>
	</footer>
</body>
</html>